// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package schemas

type Step struct {
	Id string `json:"id"`

	Description string `json:"description"`

	Ai_function string `json:"ai_function"`

	Status string `json:"status"`

	Success_criteria []any/* CUE closed list */ `json:"success_criteria"`
}

type Phase struct {
	Status string `json:"status"`

	Modifiable bool `json:"modifiable,omitempty"`

	Steps []any/* CUE closed list */ `json:"steps"`
}

type Project struct {
	ProjectName string `json:"projectName"`

	Template struct {
		Source string `json:"source"`

		Version string `json:"version"`
	} `json:"template"`

	Status string `json:"status"`

	// Currently active task context for convenience. Optional.
	ActiveTask string `json:"activeTask,omitempty"`

	// Registry of known tasks
	Tasks map[string]struct {
		Path string `json:"path"`

		Phase string `json:"phase"`

		Status string `json:"status"`

		Template_version string `json:"template_version"`

		Created_at string `json:"created_at,omitempty"`

		Completed_at string `json:"completed_at,omitempty"`
	} `json:"tasks,omitempty"`
}

type Task struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Created_at string `json:"created_at,omitempty"`

	Current_phase string `json:"current_phase"`

	Status string `json:"status"`

	Phases struct {
		Planning Phase `json:"planning"`

		Implementation Phase `json:"implementation"`

		Validation Phase `json:"validation"`
	} `json:"phases"`
}
